export const typography = {
  fontFamily: {
    primary:   "'Open Sans', sans-serif",
    secondary: "'Montserrat', sans-serif",
  },

  fontSize: {
    xxs:     '9.5px',
    xs:      '12px',
    sm:      '14px',
    md:      '16px',
    lg:      '20px',
    xl:      '24px',
    xxl:     '34px',
    xxxl:    '48px',
    display: '60px',
    giant:   '96px',
  },

  fontWeight: {
    light:     300,
    regular:   400,
    medium:    500,
    semibold:  600,
    bold:      700,
    extrabold: 800,
    black:     900,
  },

  lineHeight: {
    xxxs:    '13px',
    xxs:     '14px',
    xs:      '16px',
    sm:      '17px',
    md:      '19px',
    lg:      '22px',
    xl:      '24px',
    xxl:     '29px',
    xxxl:    '41px',
    display: '58px',
    huge:    '73px',
    giant:   '117px',
  },

  letterSpacing: {
    normal:  '0px',
    tight:   '-3.84px', // Display 1 Strong
  },

  styles: {
    topIcon: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '9.5px',
      fontWeight:    700,
      lineHeight:    '13px',
      letterSpacing: '0px',
    },
    caption: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '12px',
      fontWeight:    400,
      lineHeight:    '16px',
      letterSpacing: '0px',
    },
    captionBold: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '12px',
      fontWeight:    700,
      lineHeight:    '16px',
      letterSpacing: '0px',
    },
    captionLink: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '12px',
      fontWeight:    400,
      lineHeight:    '16px',
      letterSpacing: '0px',
    },
    overline: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '12px',
      fontWeight:    400,
      lineHeight:    '14px',
      letterSpacing: '0px',
    },
    overlineBold: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '12px',
      fontWeight:    700,
      lineHeight:    '14px',
      letterSpacing: '0px',
    },
    overlineUpper: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '12px',
      fontWeight:    400,
      lineHeight:    '14px',
      letterSpacing: '0px',
      textTransform: 'uppercase',
    },
    button: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '14px',
      fontWeight:    500,
      lineHeight:    '17px',
      letterSpacing: '0px',
    },
    buttonSemiBold: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '14px',
      fontWeight:    600,
      lineHeight:    '17px',
      letterSpacing: '0px',
    },
    body2: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '14px',
      fontWeight:    400,
      lineHeight:    '19px',
      letterSpacing: '0px',
    },
    body2Bold: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '14px',
      fontWeight:    700,
      lineHeight:    '19px',
      letterSpacing: '0px',
    },
    body2Link: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '14px',
      fontWeight:    400,
      lineHeight:    '19px',
      letterSpacing: '0px',
    },
    subtitle2: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '14px',
      fontWeight:    600,
      lineHeight:    '17px',
      letterSpacing: '0px',
    },
    body1: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '16px',
      fontWeight:    400,
      lineHeight:    '22px',
      letterSpacing: '0px',
    },
    body1Bold: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '16px',
      fontWeight:    700,
      lineHeight:    '22px',
      letterSpacing: '0px',
    },
    body1Link: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '16px',
      fontWeight:    400,
      lineHeight:    '22px',
      letterSpacing: '0px',
    },
    subtitle1: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '16px',
      fontWeight:    600,
      lineHeight:    '19px',
      letterSpacing: '0px',
    },
    title2: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '20px',
      fontWeight:    600,
      lineHeight:    '24px',
      letterSpacing: '0px',
    },
    title2Strong: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '20px',
      fontWeight:    700,
      lineHeight:    '24px',
      letterSpacing: '0px',
    },
    title1: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '24px',
      fontWeight:    600,
      lineHeight:    '29px',
      letterSpacing: '0px',
    },
    title1Strong: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '24px',
      fontWeight:    800,
      lineHeight:    '29px',
      letterSpacing: '0px',
    },
    display4: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '34px',
      fontWeight:    500,
      lineHeight:    '41px',
      letterSpacing: '0px',
    },
    display4Strong: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '34px',
      fontWeight:    800,
      lineHeight:    '41px',
      letterSpacing: '0px',
    },
    display3: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '48px',
      fontWeight:    500,
      lineHeight:    '58px',
      letterSpacing: '0px',
    },
    display3Strong: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '48px',
      fontWeight:    900,
      lineHeight:    '58px',
      letterSpacing: '0px',
    },
    display2: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '60px',
      fontWeight:    400,
      lineHeight:    '73px',
      letterSpacing: '0px',
    },
    display2Strong: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '60px',
      fontWeight:    800,
      lineHeight:    '73px',
      letterSpacing: '0px',
    },
    display1: {
      fontFamily:    "'Montserrat', sans-serif",
      fontSize:      '96px',
      fontWeight:    300,
      lineHeight:    '117px',
      letterSpacing: '0px',
    },
    display1Strong: {
      fontFamily:    "'Open Sans', sans-serif",
      fontSize:      '96px',
      fontWeight:    800,
      lineHeight:    '117px',
      letterSpacing: '-3.84px',
    },
  },
};
